version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.36.0
    working_directory: ~/repo
    # Steps to the job
    steps:
      - checkout
      - run:
          npm i -D @playwright/test
      - run:
          npx playwright install --with-deps chrome
      - run:
          name: Check Lint
          command:
            npm run lint-check
      - run:
          name: Run API and E2E tests
          command:
            PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml MARVEL_PRIVATE_KEY=$MARVEL_PRIVATE_KEY MARVEL_PUBLIC_KEY=$MARVEL_PUBLIC_KEY npx playwright test --reporter=junit
          environment:
            PLAYWRIGHT_JUNIT_OUTPUT_DIR: ~/test-results
            PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/playwright-report
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test